import 'dart:io';
import 'dart:typed_data';

import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import 'sort_controller.dart';

/// All folders and documents live as real directories/files under
/// `<app documents dir>/DocManager/<folder>/<subfolder>/.../<file>`. Using
/// the filesystem directly (instead of a database) means the folder
/// structure the user sees is exactly what's on disk - nothing to migrate
/// or corrupt, and subfolders fall out naturally since any folder can
/// contain more folders.
class StorageService {
  static Directory? _root;

  static Future<Directory> rootDir() async {
    if (_root != null) return _root!;
    final docs = await getApplicationDocumentsDirectory();
    final root = Directory(p.join(docs.path, 'DocManager'));
    if (!await root.exists()) {
      await root.create(recursive: true);
    }
    _root = root;
    return root;
  }

  static Future<List<Directory>> listFolders() async {
    final root = await rootDir();
    return listSubfolders(root);
  }

  static Future<List<Directory>> listSubfolders(Directory parent) async {
    final entries = await parent.list().toList();
    final folders = entries.whereType<Directory>().toList();
    _sortEntries(folders);
    return folders;
  }

  static Future<Directory> createFolder(String name) async {
    final root = await rootDir();
    return createSubfolder(root, name);
  }

  static Future<Directory> createSubfolder(Directory parent, String name) async {
    final dir = Directory(p.join(parent.path, _sanitize(name)));
    if (await dir.exists()) {
      throw Exception('A folder named "$name" already exists');
    }
    return dir.create(recursive: true);
  }

  static Future<void> renameFolder(Directory folder, String newName) async {
    final parentPath = p.dirname(folder.path);
    final newPath = p.join(parentPath, _sanitize(newName));
    if (await Directory(newPath).exists()) {
      throw Exception('A folder named "$newName" already exists');
    }
    await folder.rename(newPath);
  }

  static Future<void> deleteFolder(Directory folder) async {
    await folder.delete(recursive: true);
  }

  static Future<List<File>> listDocuments(Directory folder) async {
    final entries = await folder.list().toList();
    final files = entries.whereType<File>().toList();
    _sortEntries(files);
    return files;
  }

  static void _sortEntries<T extends FileSystemEntity>(List<T> entries) {
    switch (SortController.order.value) {
      case SortOrder.name:
        entries.sort(
          (a, b) => p.basename(a.path).toLowerCase().compareTo(
            p.basename(b.path).toLowerCase(),
          ),
        );
      case SortOrder.dateNewest:
        entries.sort(
          (a, b) => b.statSync().modified.compareTo(a.statSync().modified),
        );
    }
  }

  /// Copies an external file (picked from camera/gallery/file picker) into
  /// [folder], giving it a collision-proof, timestamped name while keeping
  /// its original extension.
  static Future<File> importFile(Directory folder, String sourcePath) async {
    final ext = p.extension(sourcePath);
    final base = p.basenameWithoutExtension(sourcePath);
    final stamp = DateTime.now().millisecondsSinceEpoch;
    final destPath = p.join(folder.path, '${_sanitize(base)}_$stamp$ext');
    return File(sourcePath).copy(destPath);
  }

  /// Writes generated bytes (e.g. a freshly built scan PDF) into [folder]
  /// under [fileName], making the name collision-proof if needed.
  static Future<File> saveBytes(
    Directory folder,
    String fileName,
    Uint8List bytes,
  ) async {
    final ext = p.extension(fileName);
    final base = p.basenameWithoutExtension(fileName);
    var destPath = p.join(folder.path, fileName);
    if (await File(destPath).exists()) {
      final stamp = DateTime.now().millisecondsSinceEpoch;
      destPath = p.join(folder.path, '${_sanitize(base)}_$stamp$ext');
    }
    return File(destPath).writeAsBytes(bytes);
  }

  static Future<void> deleteDocument(File file) async {
    if (await file.exists()) {
      await file.delete();
    }
  }

  static bool isImage(File file) {
    final ext = p.extension(file.path).toLowerCase();
    return ext == '.jpg' ||
        ext == '.jpeg' ||
        ext == '.png' ||
        ext == '.heic' ||
        ext == '.webp' ||
        ext == '.gif' ||
        ext == '.bmp';
  }

  static bool isVideo(File file) {
    final ext = p.extension(file.path).toLowerCase();
    return ext == '.mp4' ||
        ext == '.mov' ||
        ext == '.m4v' ||
        ext == '.avi' ||
        ext == '.mkv' ||
        ext == '.webm' ||
        ext == '.3gp';
  }

  static String _sanitize(String name) {
    final trimmed = name.trim();
    if (trimmed.isEmpty) {
      throw Exception('Name cannot be empty');
    }
    return trimmed.replaceAll(RegExp(r'[\\/:*?"<>|]'), '_');
  }
}
